[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# SPA fallback (all routes -> index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security + embed headers (allow Google Calendar appointment iframe)
[[headers]]
  for = "/index.html"
  [headers.values]
    X-Frame-Options = "ALLOWALL"
    Content-Security-Policy = "frame-ancestors 'self' https://calendar.google.com https://*.google.com" 